name: "Backend/Terraform Deployment for kubafara.pl"

on:
  push:
    branches:
      - main

jobs:
  terraform-plan-and-apply:
    name: "Terraform Init, Plan, and Apply"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: infra
    steps:
        - name: Checkout Repository Code
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          id: init
          run: terraform init
        
        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color

        - name: Terraform Format
          run: terraform fmt -check
        
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color

        - name: Terraform Apply
          run: terraform apply -auto-approve